### PR TITLE
Update to latest version (riak_core 2.0.2), improve README add LICENSE file

### PR DESCRIPTION
**Pull request by marianoguerra**
the title says it all :)

### CODE REVIEW

**Comment by Licenser** [comment]
Would love to merge but the merge introduces a number of changes  in src/chash.erl that are nothing but adding tailing whitecaps or change indentation from spaces to tabs, can you fix that before I merge?

**Comment by marianoguerra** [comment]
I will without problem, just note that this is a straight copy from riak_core sources :) (unless vim added them for some weird reason)

**Comment by Licenser** [comment]
Wooh! thanks for bearing with the picky-ness ;)!

**Comment by marianoguerra** [comment]
thank you for saving me some work creating this repo before I do :D

**Pull request merged**
